spring:
  profiles:
  active:
  - dev
---
spring
  profiles: dev # 开发环境
  application:
    name: microservicecloud-config-xhr-dev
---
spring
  profiles: test # 开发环境
  application:
    name: microservicecloud-config-xhr-test
# 请保存为UTF-8格式